-- MySQL Script generated by MySQL Workbench
-- Tue Sep 22 08:22:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Tienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tienda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tienda` (
  `idTienda` INT NOT NULL,
  `T_nombre` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `T_telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTienda`),
  UNIQUE INDEX `idTienda_UNIQUE` (`idTienda` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `idProducto` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `P_descripcion` VARCHAR(45) NOT NULL,
  `Cantidad` VARCHAR(45) NOT NULL,
  `Costo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `U_telefono` VARCHAR(45) NOT NULL,
  `Tienda_idTienda` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Tienda1_idx` (`Tienda_idTienda` ASC),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC),
  CONSTRAINT `fk_Usuario_Tienda1`
    FOREIGN KEY (`Tienda_idTienda`)
    REFERENCES `mydb`.`Tienda` (`idTienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`inventario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`inventario` (
  `Tienda_idTienda` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  PRIMARY KEY (`Tienda_idTienda`, `Producto_idProducto`),
  INDEX `fk_Tienda_has_Producto_Producto1_idx` (`Producto_idProducto` ASC),
  INDEX `fk_Tienda_has_Producto_Tienda1_idx` (`Tienda_idTienda` ASC),
  CONSTRAINT `fk_Tienda_has_Producto_Tienda1`
    FOREIGN KEY (`Tienda_idTienda`)
    REFERENCES `mydb`.`Tienda` (`idTienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tienda_has_Producto_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reporte` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reporte` (
  `idReportes` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `fecha_inicial` DATE NOT NULL,
  `cantidad_total` INT NOT NULL,
  `cantidad_especifica` INT NOT NULL,
  `inventario_Tienda_idTienda` INT NOT NULL,
  `inventario_Producto_idProducto` INT NOT NULL,
  PRIMARY KEY (`idReportes`),
  INDEX `fk_Reportes_inventario1_idx` (`inventario_Tienda_idTienda` ASC, `inventario_Producto_idProducto` ASC),
  CONSTRAINT `fk_Reportes_inventario1`
    FOREIGN KEY (`inventario_Tienda_idTienda` , `inventario_Producto_idProducto`)
    REFERENCES `mydb`.`inventario` (`Tienda_idTienda` , `Producto_idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`factura_venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`factura_venta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`factura_venta` (
  `idFactura` INT NOT NULL,
  `F_descripcion` VARCHAR(45) NOT NULL,
  `F_fecha` VARCHAR(45) NOT NULL,
  `cantidad` INT NOT NULL,
  `total` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `fk_Factura_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Factura_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Rol` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Rol` (
  `idRol` INT NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idRol`),
  INDEX `fk_Rol_Usuario1_idx` (`Usuario_idUsuario` ASC),
  UNIQUE INDEX `idRol_UNIQUE` (`idRol` ASC),
  CONSTRAINT `fk_Rol_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nomina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Nomina` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Nomina` (
  `idNomina` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `dias_trabajados` INT NOT NULL,
  `sueldo_basico` INT NOT NULL,
  `liquidacion_total` INT NOT NULL,
  `Tienda_idTienda` INT NOT NULL,
  PRIMARY KEY (`idNomina`),
  INDEX `fk_Nomina_Tienda1_idx` (`Tienda_idTienda` ASC),
  CONSTRAINT `fk_Nomina_Tienda1`
    FOREIGN KEY (`Tienda_idTienda`)
    REFERENCES `mydb`.`Tienda` (`idTienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Servicio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Servicio` (
  `nombreServicio` INT NOT NULL,
  `descripcion` VARCHAR(99) NOT NULL,
  `precio` INT NOT NULL,
  `Tienda_idTienda` INT NOT NULL,
  PRIMARY KEY (`nombreServicio`),
  INDEX `fk_Servicio_Tienda1_idx` (`Tienda_idTienda` ASC),
  CONSTRAINT `fk_Servicio_Tienda1`
    FOREIGN KEY (`Tienda_idTienda`)
    REFERENCES `mydb`.`Tienda` (`idTienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Impuesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Impuesto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Impuesto` (
  `idIimpuestos` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `costo` INT NOT NULL,
  `Tienda_idTienda` INT NOT NULL,
  PRIMARY KEY (`idIimpuestos`),
  INDEX `fk_Impuesto_Tienda1_idx` (`Tienda_idTienda` ASC),
  CONSTRAINT `fk_Impuesto_Tienda1`
    FOREIGN KEY (`Tienda_idTienda`)
    REFERENCES `mydb`.`Tienda` (`idTienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factura_has_Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Factura_has_Producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Factura_has_Producto` (
  `Factura_idFactura` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  PRIMARY KEY (`Factura_idFactura`, `Producto_idProducto`),
  INDEX `fk_Factura_has_Producto_Producto1_idx` (`Producto_idProducto` ASC),
  INDEX `fk_Factura_has_Producto_Factura1_idx` (`Factura_idFactura` ASC),
  CONSTRAINT `fk_Factura_has_Producto_Factura1`
    FOREIGN KEY (`Factura_idFactura`)
    REFERENCES `mydb`.`factura_venta` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_has_Producto_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proveedor` (
  `nit` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `cel` INT(9) NOT NULL,
  PRIMARY KEY (`nit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`factura_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`factura_compra` ;

CREATE TABLE IF NOT EXISTS `mydb`.`factura_compra` (
  `idFactura` INT NOT NULL,
  `F_descripcion` VARCHAR(45) NOT NULL,
  `F_fecha` VARCHAR(45) NOT NULL,
  `inventario_Tienda_idTienda` INT NOT NULL,
  `inventario_Producto_idProducto` INT NOT NULL,
  `proveedor_nit` INT NOT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `fk_factura_compra_inventario1_idx` (`inventario_Tienda_idTienda` ASC, `inventario_Producto_idProducto` ASC),
  INDEX `fk_factura_compra_proveedor1_idx` (`proveedor_nit` ASC),
  CONSTRAINT `fk_factura_compra_inventario1`
    FOREIGN KEY (`inventario_Tienda_idTienda` , `inventario_Producto_idProducto`)
    REFERENCES `mydb`.`inventario` (`Tienda_idTienda` , `Producto_idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_compra_proveedor1`
    FOREIGN KEY (`proveedor_nit`)
    REFERENCES `mydb`.`proveedor` (`nit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
